### ISSUE TITLE
Consistency with upstream rhel7-atomic container

### ISSUE THREAD

**Issue by jeremyeder** [kbsingh/atomic-container#12]
Hi, this issue is to discuss if this container should be direct downstream copy of rhel7-atomic image.

* Same kickstart file as upstream
* Should have same download size and same on-disk footprint as upstream
* Ongoing maintenance/ownership to track upstream changes
* Naming should match upstream

**Comment by mohammedzee1000** [comment]
@jeremyeder so what would you recommend the name to be centos-atomic or centos7-atomic?

**Comment by jeremyeder** [comment]
Since the rhel one is rhel7-atomic, yes, I would recommend centos7-atomic.  More importantly is that we tie in with the RH owners of the rhel7-atomic image to see about how to keep things in sync.  I think Ben Breard might be a good starting point of contact.

**Comment by mohammedzee1000** [comment]
@jeremyeder sounds good to me. I will take this name and work it through making it available on registry.centos.org right away.

**Comment by kbsingh** [comment]
+1 to rename to centos7-atomic, while the wider conversation takes place. 

Alsop, Can you CC in @jeremyeder @bamachrn  and myself into the conversation with Ben  @mohammedzee1000 ?

**Comment by mohammedzee1000** [comment]
I am working on pushing this container in as registry.centos.org/kbsingh/centos7-atomic atm (https://github.com/CentOS/container-index/pull/260). Once we move this into centos namespace over here, we get get it as centos/centos7-atomic.

Currently working on getting that image up. Will update once available.

**Comment by mohammedzee1000** [comment]
The image is tied into pipeline as kbsingh/cenots7-atomic. Will move to centos namespace at @kbsingh discretion.

**Comment by mohammedzee1000** [comment]
The image is now following the naming convention matching upstream. The change of namespace i think is beyond the scope of this issue, closing the same
